# This is a basic workflow to help you get started with Actions

name: Pipeline Dev

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "Dev" ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - name: Print URL
        run: echo "Teste ${{ vars.URL }}"
      - name: Print Senha
        run: echo "Teste ${{secrets.senha}}"
